### ISSUE TITLE
Different ESP Module

### ISSUE THREAD

**Issue by marcojk** [dudanov/midea-open-dongle#2]
Hi! Thanks for your work!
I've plenty of ESP01-S modules around and I'd like to use them in the dongle.
Could you share the schematics so that i can fit in the proper connector?

**Comment by dudanov** [comment]
[schematics](https://github.com/dudanov/midea-open-dongle/blob/main/schematic.pdf)

**Comment by marcojk** [comment]
Sorry, I meant the project file of Kicad or EasyEda; I'd like to maintain your pretty layout

**Comment by dudanov** [comment]
[kicad.zip](https://github.com/dudanov/midea-open-dongle/files/6779372/kicad.zip)
